### ISSUE TITLE
Add observing script

### ISSUE THREAD

**Issue by nbudaiev** [ACES-CMZ/TENS#1]
A script copied from 18A-014.

[zz__from18A-014_rasterMosaic.txt](https://github.com/ACES-CMZ/TENS/files/11113883/zz__from18A-014_rasterMosaic.txt)

**Comment by keflavich** [comment]
@nbudaiev could you make this a PR and find a home for it?  I leave it to you to figure out the organization.

**Comment by nbudaiev** [comment]
File uploaded
